export const SIXTEEN_CUBE = [
  [
    { letter: "A", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "A", isDouble: false },
    { letter: "N", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "G", isDouble: false },
  ],
  [
    { letter: "A", isDouble: false },
    { letter: "H", isDouble: false },
    { letter: "S", isDouble: false },
    { letter: "P", isDouble: false },
    { letter: "C", isDouble: false },
    { letter: "O", isDouble: false },
  ],
  [
    { letter: "A", isDouble: false },
    { letter: "S", isDouble: false },
    { letter: "P", isDouble: false },
    { letter: "F", isDouble: false },
    { letter: "F", isDouble: false },
    { letter: "K", isDouble: false },
  ],
  [
    { letter: "O", isDouble: false },
    { letter: "B", isDouble: false },
    { letter: "J", isDouble: false },
    { letter: "O", isDouble: false },
    { letter: "A", isDouble: false },
    { letter: "B", isDouble: false },
  ],
  [
    { letter: "I", isDouble: false },
    { letter: "O", isDouble: false },
    { letter: "T", isDouble: false },
    { letter: "M", isDouble: false },
    { letter: "U", isDouble: false },
    { letter: "C", isDouble: false },
  ],
  [
    { letter: "R", isDouble: false },
    { letter: "Y", isDouble: false },
    { letter: "V", isDouble: false },
    { letter: "D", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "L", isDouble: false },
  ],
  [
    { letter: "L", isDouble: false },
    { letter: "R", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "I", isDouble: false },
    { letter: "X", isDouble: false },
    { letter: "D", isDouble: false },
  ],
  [
    { letter: "E", isDouble: false },
    { letter: "I", isDouble: false },
    { letter: "U", isDouble: false },
    { letter: "N", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "S", isDouble: false },
  ],
  [
    { letter: "W", isDouble: false },
    { letter: "N", isDouble: false },
    { letter: "G", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "H", isDouble: false },
  ],
  [
    { letter: "L", isDouble: false },
    { letter: "N", isDouble: false },
    { letter: "H", isDouble: false },
    { letter: "N", isDouble: false },
    { letter: "R", isDouble: false },
    { letter: "Z", isDouble: false },
  ],
  [
    { letter: "T", isDouble: false },
    { letter: "S", isDouble: false },
    { letter: "T", isDouble: false },
    { letter: "I", isDouble: false },
    { letter: "Y", isDouble: false },
    { letter: "D", isDouble: false },
  ],
  [
    { letter: "O", isDouble: false },
    { letter: "W", isDouble: false },
    { letter: "T", isDouble: false },
    { letter: "O", isDouble: false },
    { letter: "A", isDouble: false },
    { letter: "T", isDouble: false },
  ],
  [
    { letter: "E", isDouble: false },
    { letter: "R", isDouble: false },
    { letter: "T", isDouble: false },
    { letter: "T", isDouble: false },
    { letter: "Y", isDouble: false },
    { letter: "L", isDouble: false },
  ],
  [
    { letter: "T", isDouble: false },
    { letter: "O", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "S", isDouble: false },
    { letter: "S", isDouble: false },
    { letter: "I", isDouble: false },
  ],
  [
    { letter: "T", isDouble: false },
    { letter: "E", isDouble: false },
    { letter: "R", isDouble: false },
    { letter: "W", isDouble: false },
    { letter: "H", isDouble: false },
    { letter: "V", isDouble: false },
  ],
  [
    { letter: "N", isDouble: false },
    { letter: "U", isDouble: false },
    { letter: "I", isDouble: false },
    { letter: "H", isDouble: false },
    { letter: "M", isDouble: false },
    { letter: "QU", isDouble: false },
  ],
];
